In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [4]:
dataset = pd.read_csv('credit_card_defaulter.csv')
dataset.head()

,Unnamed: 0,default,student,balance,income
0,1,No,No,729.526495,44361.62507
1,2,No,Yes,817.180407,12106.13470
2,3,No,No,1073.549164,31767.13895
3,4,No,No,529.250605,35704.49394
4,5,No,No,785.655883,38463.49588


In [5]:
dataset.shape

(10000, 5)

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  10000 non-null  int64  
 1   default     10000 non-null  object 
 2   student     10000 non-null  object 
 3   balance     10000 non-null  float64
 4   income      10000 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 390.8+ KB


In [7]:
dataset.isnull().sum()

,0
Unnamed: 0,0
default,0
student,0
balance,0
income,0


In [8]:
dataset.describe()

,Unnamed: 0,balance,income
count,10000.00000,10000.000000,10000.000000
mean,5000.50000,835.374886,33516.981876
std,2886.89568,483.714985,13336.639563
min,1.00000,0.000000,771.967729
25%,2500.75000,481.731105,21340.462905
50%,5000.50000,823.636973,34552.644800
75%,7500.25000,1166.308387,43807.729275
max,10000.00000,2654.322576,73554.233500


In [9]:
(dataset.balance == 0).sum(axis=0)

np.int64(499)

In [10]:
dataset.student.value_counts()

,count
student,
No,7056
Yes,2944


In [11]:
dataset.default.value_counts()

,count
default,
No,9667
Yes,333


In [12]:
dataset['student2'] = dataset.student.factorize()[0]




In [13]:
dataset['default2'] = dataset.default.factorize()[0]
dataset.head()

,Unnamed: 0,default,student,balance,income,student2,default2
0,1,No,No,729.526495,44361.62507,0,0
1,2,No,Yes,817.180407,12106.13470,1,0
2,3,No,No,1073.549164,31767.13895,0,0
3,4,No,No,529.250605,35704.49394,0,0
4,5,No,No,785.655883,38463.49588,0,0


In [14]:
x = dataset.iloc[:, 3:6].values
y = dataset.iloc[:, -1].values
print(x)
print(y)

[[7.29526495e+02 4.43616251e+04 0.00000000e+00]
 [8.17180407e+02 1.21061347e+04 1.00000000e+00]
 [1.07354916e+03 3.17671390e+04 0.00000000e+00]
 ...
 [8.45411989e+02 5.86361570e+04 0.00000000e+00]
 [1.56900905e+03 3.66691124e+04 0.00000000e+00]
 [2.00922183e+02 1.68629523e+04 1.00000000e+00]]
[0 0 0 ... 0 0 0]


In [15]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20, random_state=0)
print(x_train, x_test, y_train, y_test )

[[1.01489113e+03 1.52533116e+04 1.00000000e+00]
 [1.02058903e+03 1.30949457e+04 1.00000000e+00]
 [1.09035035e+03 4.82809463e+04 0.00000000e+00]
 ...
 [6.87064419e+02 1.40594576e+04 1.00000000e+00]
 [4.60102253e+01 1.39500870e+04 1.00000000e+00]
 [3.37576000e+02 5.21922747e+04 0.00000000e+00]] [[0.00000000e+00 1.39114413e+04 1.00000000e+00]
 [3.96985985e+02 5.54546310e+04 0.00000000e+00]
 [1.04641667e+03 4.75983074e+04 0.00000000e+00]
 ...
 [1.74087005e+03 1.74780313e+04 1.00000000e+00]
 [4.98749451e+02 5.16900635e+04 0.00000000e+00]
 [1.02259834e+03 1.17390960e+04 1.00000000e+00]] [0 0 0 ... 0 0 0] [0 0 0 ... 0 0 0]


In [17]:
import sklearn.linear_model as skl_lm
clf = skl_lm.LogisticRegression(solver='newton-cg')
clf.fit(x_train, y_train)

LogisticRegression(solver='newton-cg')

In [18]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [19]:
y_pred = clf.predict(x_test)
print(y_pred)

[0 0 0 ... 0 0 0]


In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1920    6]
 [  52   22]]


In [21]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)

0.971


In [22]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
print(y_pred)

[0 0 0 ... 0 0 0]


In [23]:
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y_test, y_pred)
print(cm1)

[[1919    7]
 [  60   14]]


In [25]:
from sklearn.metrics import accuracy_score
ac1 = accuracy_score(y_test, y_pred)
print(ac1)

0.9665
